replicaCount: 1

fullName: node-helm
name: node-helm
chart: node-helm

image:
  repository: nathan/node-helm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3333

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - 0.0.0.0
  tls: []

resources:
  limits:
    cpu: 700m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 384Mi

nodeSelector: {}

tolerations: []

affinity: {}