apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Values.chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}